// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dao

// Injectors from wire.go:

func newTestDao() (*dao, func(), error) {
	redis, cleanup, err2 := NewRedis()
	if err2 != nil {
		return nil, nil, err
	}
	memcache, cleanup2, err2 := NewMC()
	if err2 != nil {
		cleanup()
		return nil, nil, err
	}
	db, cleanup3, err2 := NewDB()
	if err2 != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bcos, cleanup4, err2 := NewBC()
	if err2 != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, cleanup5, err2 := NewMongo()
	if err2 != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	daoDao, cleanup6, err2 := newDao(redis, memcache, db, bcos, client)
	if err2 != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return daoDao, func() {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
